controller_list:
  - name: fake_xarm6_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - finger_joint
      - right_crank_joint
      - left_proximal_phalanx_joint
      - right_proximal_phalanx_joint

