controller_list:
  - name: fake_xarm6_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
      - right_crank_joint
      - left_proximal_phalanx_joint
      - right_proximal_phalanx_joint
initial:  # Define initial robot poses.
  - group: xarm6
    pose: home
  - group: gripper
    pose: open