# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: xarm6
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - finger_joint
    - right_crank_joint
    - left_proximal_phalanx_joint
    - right_proximal_phalanx_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: xarm6_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - finger_joint
      - right_crank_joint
      - left_proximal_phalanx_joint
      - right_proximal_phalanx_joint